context:
  version: 1.15.0

package:
  name: coffeesense-language-server
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/coffeesense-language-server/-/coffeesense-language-server-${{ version }}.tgz
  sha256: 9df86df6e90dce25d1906c33c4c0d6a0a73bea1e011028a699c08b832560f739

build:
  number: 0
  noarch: generic

requirements:
  build:
    - git
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - coffeesense-language-server &
      - exe_pid=$!
      - "trap \"kill -SIGTERM ${exe_pid}\" SIGTERM"

about:
  license: MIT
  license_file:
    - LICENSE
    - third-party-licenses.txt
  summary: IntelliSense for CoffeeScript. LSP implementation / VSCode extension
  homepage: https://github.com/phil294/coffeesense-language-server
  repository: https://github.com/phil294/coffeesense-language-server

extra:
  recipe-maintainers:
    - danielnachun
